apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-quota
  namespace: dev
spec:
  # Hard limits for compute resources
  hard:
    # CPU limits
    requests.cpu: "20"
    limits.cpu: "40"

    # Memory limits
    requests.memory: "40Gi"
    limits.memory: "80Gi"

    # Storage limits
    requests.storage: "100Gi"
    persistentvolumeclaims: "10"

    # Pod limits
    pods: "50"

    # Service limits
    services: "20"
    services.loadbalancers: "2"
    services.nodeports: "5"

    # ConfigMap and Secret limits
    configmaps: "50"
    secrets: "50"

  # Scope selectors (optional)
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - low
      - medium

---
# Object count quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-object-quota
  namespace: dev
spec:
  hard:
    # Deployment limits
    count/deployments.apps: "20"
    count/statefulsets.apps: "10"
    count/jobs.batch: "30"
    count/cronjobs.batch: "10"

    # Ingress limits
    count/ingresses.networking.k8s.io: "10"

---
# LimitRange to set default resource limits
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
spec:
  limits:
  # Container limits
  - type: Container
    default:
      # Default limits (if not specified)
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      # Default requests (if not specified)
      cpu: "100m"
      memory: "128Mi"
    max:
      # Maximum allowed
      cpu: "4"
      memory: "8Gi"
    min:
      # Minimum required
      cpu: "10m"
      memory: "16Mi"

  # Pod limits
  - type: Pod
    max:
      cpu: "8"
      memory: "16Gi"

  # PVC limits
  - type: PersistentVolumeClaim
    max:
      storage: "20Gi"
    min:
      storage: "1Gi"