apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-namespace
  namespace: argocd
  labels:
    app.kubernetes.io/name: dev-namespace
    app.kubernetes.io/component: infrastructure
    environment: dev
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  # Finalizers ensure proper cleanup
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Project this application belongs to
  project: default

  # Source repository configuration
  source:
    # Git repository URL
    repoURL: https://github.com/yourorg/infrastructure-apps.git
    # Target revision (branch, tag, or commit)
    targetRevision: main
    # Path to the dev overlay
    path: dev-namespace/overlays/dev

  # Destination cluster and namespace
  destination:
    # Cluster URL (in-cluster)
    server: https://kubernetes.default.svc
    # Target namespace (dev namespace will be created)
    namespace: dev

  # Sync policy
  syncPolicy:
    # Automated sync configuration
    automated:
      # Automatically sync when Git changes
      prune: true
      # Automatically sync when cluster state changes
      selfHeal: true
      # Allow empty directories
      allowEmpty: false

    # Sync options
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true

    # Retry configuration
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences for specific fields
  ignoreDifferences:
  - group: ""
    kind: ResourceQuota
    jsonPointers:
    - /status  # Ignore ResourceQuota status