apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-prod-fixed
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://8gears.container-registry.com/library/n8n
    chart: n8n
    targetRevision: "1.0.0"
    helm:
      values: |
        ingress:
          enabled: false

        main:
          config:
            db:
              type: postgresdb
              postgresdb:
                host: n8n-postgresql
                database: n8n_db
                user: n8n_user
          secret:
            db:
              postgresdb:
                password: n8nProdPass123!
          env:
            - name: N8N_SECURE_COOKIE
              value: "false"
          service:
            type: LoadBalancer
            port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true