apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
    environment: staging
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "deployments"
  # Finalizers ensure proper cleanup
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Project this application belongs to
  project: default

  # Source repository configuration
  source:
    # Git repository URL
    repoURL: https://github.com/james-agentifyhq/agentifyhq-infra-apps.git
    # Target revision (branch, tag, or commit)
    targetRevision: main
    # Path to the staging overlay
    path: n8n/overlays/staging

  # Destination cluster and namespace
  destination:
    # Cluster URL (in-cluster)
    server: https://kubernetes.default.svc
    # Target namespace
    namespace: n8n-staging

  # Sync policy
  syncPolicy:
    # Automated sync configuration
    automated:
      # Automatically sync when Git changes
      prune: true
      # Automatically sync when cluster state changes
      selfHeal: true
      # Allow empty directories
      allowEmpty: false

    # Sync options
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=true

    # Retry configuration
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences for specific fields
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas  # Ignore replica count (managed by HPA)
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
    - .spec.volumeClaimTemplates[]?.status

  # Health assessment
  # Custom health checks can be defined here if needed