apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://8gears.github.io/n8n-helm-chart/
    chart: n8n
    targetRevision: "1.0.15"
    helm:
      values: |
        ingress:
          enabled: false

        main:
          config:
            db:
              type: postgresdb
              postgresdb:
                host: n8n-postgresql
                database: n8n_db
                user: n8n_user
          secret:
            db:
              postgresdb:
                password: n8nProdPass123!
          service:
            type: LoadBalancer
            port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true