apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: "1.15.11"
    helm:
      values: |
        postgresql:
          enabled: true
          postgresqlDatabase: n8n_db
          postgresqlUsername: n8n_user
          postgresqlPassword: n8nProdPass123!
          image:
            tag: "15"
        service:
          type: LoadBalancer
          port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true