# Patch for n8n deployment - staging environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  # Two replicas for staging
  replicas: 2

  template:
    spec:
      containers:
      - name: n8n
        # Medium resource requirements for staging
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi

---
# Patch for PostgreSQL StatefulSet - staging environment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: n8n
spec:
  template:
    spec:
      containers:
      - name: postgres
        # Medium resource requirements for staging
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi

  # Medium volume for staging
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

---
# Patch for n8n PVC - staging environment
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  resources:
    requests:
      storage: 5Gi

---
# Patch for IngressRoute - staging environment
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  routes:
  - match: Host(`n8n-staging.example.com`)
    kind: Rule
    services:
    - name: n8n
      port: 80
    middlewares:
    - name: security-headers