# Rate limiting middleware for production
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: n8n
spec:
  rateLimit:
    average: 100
    burst: 200
    period: 1m