# Single-node cluster fixes for n8n production
# These patches fix issues for running production overlay on single-node K3s

# Fix 1: Change postgres hostname from "postgres" to "postgres-prod"
# Fix 2: Remove hard anti-affinity requirement
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
spec:
  # Reduce to 1 replica for single node
  replicas: 1
  
  template:
    spec:
      # Fix PostgreSQL hostname in init container
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until nc -z postgres-prod 5432; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is up - continuing"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      
      containers:
      - name: n8n
        # Fix PostgreSQL hostname in environment
        env:
        - name: DB_POSTGRESDB_HOST
          value: "postgres-prod"
        - name: DB_POSTGRESDB_PORT
          value: "5432"
      
      # Override affinity to use soft anti-affinity instead of hard requirement
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - production
        # Use soft (preferred) instead of hard (required) anti-affinity
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - n8n
              topologyKey: kubernetes.io/hostname
