apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Environment-specific labels
labels:
- pairs:
    environment: dev

# No patches needed for dev environment
# Base configuration is already suitable for development