apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
spec:
  # Default replica count (overridden by overlays)
  replicas: 1

  # Deployment strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app.kubernetes.io/name: n8n
      app.kubernetes.io/component: workflow-automation

  template:
    metadata:
      labels:
        app.kubernetes.io/name: n8n
        app.kubernetes.io/component: workflow-automation
      annotations:
        # Force restart on config change
        checksum/config: "placeholder"
    spec:
      # Security context for the pod
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      # Init containers
      initContainers:
      # Set correct permissions on the data volume
      - name: volume-permissions
        image: busybox:1.36
        command: ["sh", "-c", "chown -R 1000:1000 /data"]
        volumeMounts:
        - name: n8n-data
          mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false  # Need root to chown
          runAsUser: 0
          capabilities:
            drop:
              - ALL
            add:
              - CHOWN
              - FOWNER
      # Wait for PostgreSQL to be ready
      - name: wait-for-postgres
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "=== PostgreSQL Connection Debug ==="
          echo "Target host: postgres"
          echo "Target port: 5432"
          echo "Timestamp: $(date)"

          for i in $(seq 1 30); do
            echo "Attempt $i/30: Testing connection to postgres:5432"
            if nc -z postgres 5432; then
              echo "✓ PostgreSQL is ready on postgres:5432"
              break
            else
              echo "✗ PostgreSQL not ready, waiting..."
              sleep 2
            fi
          done

          if ! nc -z postgres 5432; then
            echo "ERROR: PostgreSQL not accessible after 30 attempts"
            echo "Available services:"
            nslookup postgres || echo "DNS lookup failed"
            exit 1
          fi

          echo "✓ PostgreSQL connection verified"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL

      containers:
      - name: n8n
        # n8n image - update version as needed
        image: n8nio/n8n:latest
        imagePullPolicy: IfNotPresent

        # Security context for the container
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false  # n8n needs to write data
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL

        # Environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: n8n-config
        - secretRef:
            name: n8n-secrets

        # Additional environment variables for database connection
        env:
        - name: DB_TYPE
          value: "postgresdb"
        - name: DB_POSTGRESDB_HOST
          value: "postgres"
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        # Enhanced logging for debugging
        - name: N8N_LOG_LEVEL
          value: "debug"
        - name: N8N_LOG_OUTPUT
          value: "console"
        - name: DB_LOGGING_MAX_EXECUTION_TIME
          value: "0"
        # Database credentials - using non-root user for security
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_NON_ROOT_USER
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_NON_ROOT_PASSWORD
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB

        # Resource limits and requests (overridden by overlays)
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi

        # Health checks
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        # Startup probe for initial startup
        startupProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

        # Port configuration
        ports:
        - name: http
          containerPort: 5678
          protocol: TCP

        # Volume mounts
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        - name: tmp
          mountPath: /tmp

      # Volumes
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data
      - name: tmp
        emptyDir: {}

      # Scheduling preferences
      affinity:
        # Prefer to schedule on different nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - n8n
              topologyKey: kubernetes.io/hostname

---
# Persistent Volume Claim for n8n data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Optional: Specify storage class
  # storageClassName: fast-ssd