apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/component: workflow-automation
spec:
  entryPoints:
  - websecure

  routes:
  - match: Host(`n8n.example.com`)
    kind: Rule
    services:
    - name: n8n
      port: 80
    middlewares:
    # Security headers
    - name: security-headers

  # TLS configuration
  tls:
    secretName: n8n-tls
    # Optional: Use cert-manager annotation
    # certResolver: letsencrypt

---
# Middleware for security headers
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: n8n
spec:
  headers:
    # Security headers
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      X-Powered-By: ""
      Server: ""

---
# TLS Certificate Secret (placeholder)
# Use cert-manager to automatically generate this
apiVersion: v1
kind: Secret
metadata:
  name: n8n-tls
  namespace: n8n
type: kubernetes.io/tls
data:
  # Placeholder - replace with actual certificate or use cert-manager
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t