apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
data:
  DB_POSTGRESDB_DATABASE: bjhu  # n8n
  DB_POSTGRESDB_PASSWORD: UG9zdGdyZXMxMjM0IT8=  # Postgres1234!?
  DB_POSTGRESDB_USER: bjhuX3VzZXI=  # n8n_user
  N8N_ENCRYPTION_KEY: dGhpc2lzaG93c2VjcmV0a2V5Zm9yZW5jcnlwdGlvbg==  # thisishowsecretkeyforencryption