apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: NFBTU1Bvc3RncmVzMTIzNCE=  # MySQLPostgres123!
  POSTGRES_DB: bjhu  # n8n
  POSTGRES_NON_ROOT_USER: bjhuX3VzZXI=  # n8n_user
  POSTGRES_NON_ROOT_PASSWORD: UG9zdGdyZXMxMjM0IT8=  # Postgres1234!?