apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  # Database credentials
  # IMPORTANT: Replace these with actual SealedSecret encrypted values
  # Generate sealed secrets using:
  #   kubectl create secret generic n8n-secrets \
  #     --from-literal=DB_POSTGRESDB_DATABASE=n8n \
  #     --from-literal=DB_POSTGRESDB_USER=n8n \
  #     --from-literal=DB_POSTGRESDB_PASSWORD=changeme123 \
  #     --from-literal=N8N_ENCRYPTION_KEY=changeme456 \
  #     --dry-run=client -o yaml | \
  #   kubeseal --format yaml > sealed-secret.yaml

  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_PASSWORD: "changeme123"

  # n8n encryption key (CRITICAL: Must be persistent and secure)
  # Generate with: openssl rand -base64 32
  N8N_ENCRYPTION_KEY: "changeme456"

---
# PostgreSQL Database Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
stringData:
  # PostgreSQL credentials
  # IMPORTANT: Replace with actual SealedSecret encrypted values
  POSTGRES_DB: "n8n"
  POSTGRES_USER: "n8n"
  POSTGRES_PASSWORD: "changeme123"