apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Namespace override for dev environment
namespace: n8n-dev

# Environment-specific labels
labels:
- pairs:
    environment: dev

# Name suffix for resources
nameSuffix: -dev

# Patches for dev environment
patches:
- path: patches.yaml

# ConfigMap generator for environment-specific config
configMapGenerator:
- name: n8n-config
  behavior: replace
  literals:
  - N8N_HOST=n8n-dev.example.com
  - N8N_PORT=5678
  - N8N_PROTOCOL=https
  - GENERIC_TIMEZONE=America/New_York
  - TZ=America/New_York
  - EXECUTIONS_MODE=regular
  - EXECUTIONS_TIMEOUT=300
  - EXECUTIONS_TIMEOUT_MAX=600
  - EXECUTIONS_DATA_SAVE_ON_ERROR=all
  - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
  - EXECUTIONS_DATA_SAVE_ON_PROGRESS=false
  - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
  - QUEUE_BULL_REDIS_HOST=
  - QUEUE_BULL_REDIS_PORT=6379
  - N8N_BASIC_AUTH_ACTIVE=false
  - N8N_SECURE_COOKIE=true
  - N8N_DIAGNOSTICS_ENABLED=true
  - N8N_VERSION_NOTIFICATIONS_ENABLED=true
  - WORKFLOWS_DEFAULT_NAME=My workflow
  - N8N_WORKFLOW_TAGS_DISABLED=false
  - EXTERNAL_HOOK_FILES=
  - N8N_LOG_LEVEL=debug
  - N8N_LOG_OUTPUT=console